name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u "shrinivas1080" -p "8390500549Shri@"
        docker build -t shrinivas1080/hello-html .
        docker push shrinivas1080/hello-html
