name: Docker Image CI

on:
  push:
    branches: [ "main" ]
      
jobs:        
  build-login-publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v3
   
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: build image
        run: docker build -t vdeshkar/test-project:latest .
        
      - name: tag image with version id
        run: docker image tag vdeshkar/test-project:latest vdeshkar/test-project:1.0.2
      
      - name: push latest image
        run: docker push vdeshkar/test-project:latest

      - name: push image with Version id
        run: docker push vdeshkar/test-project:1.0.2

      - name: push README to Dockerhub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: vdeshkar/test-project
          readme-filepath: Dockerhub-README.md
