name: Docker Image CI
  

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:        
  build-login-publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: shrinivas1080
          password: 8390500549Shri@

      - name: build image
        run: docker build -t shrinivas1080/hello-html .

      - name: tag image with version id
        run: docker image tag shrinivas1080/hello-html:latest shrinivas1080/hello-html:${GITHUB_REF##*/}

      - name: push latest image
        run: docker push shrinivas1080/hello-html:latest

      - name: push image with Version id
        run: docker push shrinivas1080/hello-html:${GITHUB_REF##*/}
